### ISSUE TITLE
Make modules private

### ISSUE THREAD

**Issue by flosse** [uklotzde/infect#1]
As a library user, I prefer a flat API so I can get a quicker overview of it.
I think it's also visually easier with documentation.

Here is a brief comparison:
This is how it looks like with public modules:
![Bildschirmfoto vom 2023-03-18 16-50-42](https://user-images.githubusercontent.com/276043/226116556-a0a6a82e-447c-4bc6-be60-2f798d277c6e.png)

This is how it looks like with private modules:
![Bildschirmfoto vom 2023-03-18 16-50-53](https://user-images.githubusercontent.com/276043/226116558-e01696e5-8718-4baf-8de0-d1616412ed2d.png)

What do you think?

**Comment by uklotzde** [comment]
Fixing this revealed redundant type aliases.
