### ISSUE TITLE
Can we avoid requiring fmt::Debug for tasks?

### ISSUE THREAD

**Issue by flosse** [uklotzde/infect#2]
Here `fmt::Debug` is required 
https://github.com/uklotzde/infect/blob/7481c1759fd83c0bf20cc03fd02842d5cc10147b/src/processing.rs#L40
... so that we can log a debug message later on:
https://github.com/uklotzde/infect/blob/7481c1759fd83c0bf20cc03fd02842d5cc10147b/src/processing.rs#L81
but sometimes you might have task payloads that do not implement `Debug`.

**Comment by uklotzde** [comment]
fmt::Debug was just enforced for verbose logging. Actually not required.

Would it be worth hiding it behind feature flags, e.g. `debug-task'? The code involving the trait bounds might get ugly.

**Comment by uklotzde** [comment]
Clarified by f81b169daa5ab751e1ba41bdf4ff97a0fa8392e4
