### ISSUE TITLE
Question: How to return an effect and a task together from an handled intent?

### ISSUE THREAD

**Issue by flosse** [uklotzde/infect#3]
Let's say the intent is something like `Intent::StartComputing` and I want to send a message like `ComputingRequestAccepted` to the outside world with a task but also want to apply an effect like `Effect::SetComputingState` then currently I have to append the task to the effect so that I can return the task after the effect was applied. Is there an other way to do this more elegant?

**Comment by uklotzde** [comment]
Obsolete with v0.0.22 (383a9a57149665156d65e65ab38aac46320b0485)
